need to fix redirect and third_party detection but otherwise looking good

diff --git a/Makefile.Common b/Makefile.Common
--- a/Makefile.Common
+++ b/Makefile.Common
@@ -81,10 +81,10 @@ ALL_SRC := $(shell find $(ALL_PKG_DIRS) -name '*.go' \
                                 -not -path '*/local/*' \
                                 -type f | sort)
 
-ALL_SRC_AND_SHELL := $(shell find $(ALL_PKG_DIRS) -name '*.go' -o -name "*.sh" \
-                                -not -path '*/third_party/*' \
-                                -not -path '*/local/*' \
-                                -type f | sort)
+ALL_SRC_AND_SHELL := find . -iname '*.go' -o -iname "*.sh" \
+                                -not -path '**/third_party/*' \
+                                -not -path '**/local/*' \
+                                -type f | sort
 
 # All source code and documents. Used in spell check.
 ALL_SRC_AND_DOC := $(shell find $(ALL_PKG_DIRS) -name "*.md" -o -name "*.go" -o -name "*.yaml" \
@@ -93,6 +93,9 @@ ALL_SRC_AND_DOC := $(shell find $(ALL_PKG_DIRS) -name "*.md" -o -name "*.go" -o 
 
 # ALL_PKGS is used with 'go cover'
 ALL_PKGS := $(shell $(GOCMD) list $(sort $(dir $(ALL_SRC))))
+
+
+ADDLICENSE_CMD := $(ADDLICENSE) -s=only -y "" -c 'The OpenTelemetry Authors'
 
 pwd:
 	@pwd
@@ -147,27 +150,31 @@ benchmark:
 
 .PHONY: addlicense
 addlicense: $(ADDLICENSE)
-	@ADDLICENSEOUT=`$(ADDLICENSE) -s=only -y "" -c 'The OpenTelemetry Authors' $(ALL_SRC_AND_SHELL) 2>&1`; \
-		if [ "$$ADDLICENSEOUT" ]; then \
-			echo "$(ADDLICENSE) FAILED => add License errors:\n"; \
-			echo "$$ADDLICENSEOUT\n"; \
-			exit 1; \
-		else \
-			echo "Add License finished successfully"; \
-		fi
+	@ADDLICENSEOUT=$$(for f in $$($(ALL_SRC_AND_SHELL)); do \
+		`$(ADDLICENSE_CMD) "$$f" 2>&1`; \
+	done); \
+	if [ "$$ADDLICENSEOUT" ]; then \
+		echo "$(ADDLICENSE) FAILED => add License errors:\n"; \
+		echo "$$ADDLICENSEOUT\n"; \
+		exit 1; \
+	else \
+		echo "Add License finished successfully"; \
+	fi	
 
 .PHONY: checklicense
 checklicense: $(ADDLICENSE)
-	@licRes=$$(for f in $(ALL_SRC_AND_SHELL); do \
-	           awk '/Copyright The OpenTelemetry Authors|generated|GENERATED/ && NR<=3 { found=1; next } END { if (!found) print FILENAME }' $$f; \
-			   awk '/SPDX-License-Identifier: Apache-2.0|generated|GENERATED/ && NR<=4 { found=1; next } END { if (!found) print FILENAME }' $$f; \
-	   done); \
-	   if [ -n "$${licRes}" ]; then \
-	           echo "license header checking failed:"; echo "$${licRes}"; \
-	           exit 1; \
-		else \
-			echo "Check License finished successfully"; \
-	   fi
+	@licRes=$$(for f in $$($(ALL_SRC_AND_SHELL)); do \
+		echo "$$f"; \
+		awk '/Copyright The OpenTelemetry Authors|generated|GENERATED/ && NR<=3 { found=1; next } END { if (!found) print FILENAME }' $$f; \
+		awk '/SPDX-License-Identifier: Apache-2.0|generated|GENERATED/ && NR<=4 { found=1; next } END { if (!found) print FILENAME }' $$f; \
+		$(ADDLICENSE_CMD) -c 2&>1 && echo "$$f"; \
+		done); \
+	if [ -n "$${licRes}" ]; then \
+		echo "license header checking failed:"; echo "$${licRes}"; \
+		exit 1; \
+	else \
+		echo "Check License finished successfully"; \
+	fi
 
 .PHONY: checklinks
 checklinks:
