Initial deb and rpm packaging
- Uses https://github.com/jordansissel/fpm
- Adds `deb-package` and `rpm-package` targets to Makefile
- Builds simple deb and rpm packages that installs the otelcontribcol
binary to `/usr/bin/otelcontribcol`
- Adds deb and rpm packages to circleci workspace for github release
- TODO: create service scripts

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -187,6 +187,22 @@ workflows:
           filters:
             tags:
               only: /.*/
+      - build-package:
+          name: deb-package
+          package_type: deb
+          requires:
+            - cross-compile
+          filters:
+            tags:
+              only: /^v([0-9])+.([0-9])+.([0-9])+.*/
+      - build-package:
+          name: rpm-package
+          package_type: rpm
+          requires:
+            - cross-compile
+          filters:
+            tags:
+              only: /^v([0-9])+.([0-9])+.([0-9])+.*/
 
 jobs:
   setup:
@@ -383,3 +399,34 @@ jobs:
           path: test-results/junit
       - store_artifacts:
           path: test-results
+
+  build-package:
+    executor: golang
+    parameters:
+      package_type:
+        type: enum
+        enum: ["deb", "rpm"]
+    steps:
+      - checkout
+      - attach_to_workspace
+      - run:
+          name: Install fpm and dependencies
+          command: |
+            sudo apt-get update
+            sudo apt-get install -y ruby ruby-dev rubygems build-essential rpm
+            sudo gem install --no-document fpm -v 1.11.0
+      - run:
+          name: Build << parameters.package_type >> package
+          command: ./packaging/<< parameters.package_type >>/build.sh "${CIRCLE_TAG:-}"
+      - run:
+          name: Test << parameters.package_type >> package installation
+          command: |
+            if [[ "<< parameters.package_type >>" = "deb" ]]; then
+                sudo dpkg -i bin/otel-collector-contrib*.deb
+            else
+                sudo rpm -ivh bin/otel-collector-contrib*.rpm
+            fi
+            test -f /usr/bin/otelcontribcol || (echo "/usr/bin/otelcontribcol not found!" && exit 1)
+      - persist_to_workspace:
+          root: ~/
+          paths: project/bin
