Fix conditionals that trigger Artifact upload (#38236)
#### Description
After the revert done in
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38230
and
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38231,
I'm looking yet again on what went wrong there.

I'm solving this in small parts, and this PR focuses on ensuring JUnit
Artifacts are uploaded correctly.

#### Link to tracking issue
Still related to
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36761


#### Testing
I plan to test this by looking at the artifacts produced in this PR. The
JUnit files need to be there. See
https://github.com/actions/upload-artifact?tab=readme-ov-file#where-does-the-upload-go

---------

Signed-off-by: Arthur Silva Sens <arthursens2005@gmail.com>

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -286,22 +286,31 @@ jobs:
           path: ~/.cache/go-build
           key: go-test-build-${{ runner.os }}-${{ matrix.go-version }}-${{ matrix.runner }}-${{ hashFiles('**/go.sum') }}
       - name: Run Unit Tests
-        if: startsWith( matrix.go-version, '1.23' ) != true
+        id: tests
+        if: github.ref != 'refs/heads/main' # Runs on every PR and both go versions
         run: make gotest GROUP=${{ matrix.group }}
       - name: Run Unit Tests With JUnit and Coverage
-        if: startsWith( matrix.go-version, '1.23' ) # only run junit/coverage on one version
+        id: tests-with-junit
+        if: startsWith( matrix.go-version, '~1.23' ) && github.ref == 'refs/heads/main' && github.event_name == 'push' # only run junit/coverage on one version and only on main
+        continue-on-error: true # Allow uploading artifacts even if the test fails
         run: make gotest-with-junit-and-cover GROUP=${{ matrix.group }}
       - uses: actions/upload-artifact@v4
-        if: startsWith( matrix.go-version, '1.23' ) # only upload artifact for one version
+        if: startsWith( matrix.go-version, '~1.23' ) && github.ref == 'refs/heads/main' && github.event_name == 'push' # only upload artifact for one version and only on main
         with:
           name: coverage-artifacts-${{ matrix.go-version }}-${{ matrix.runner }}-${{ matrix.group }}
           path: ${{ matrix.group }}-coverage.txt
       - uses: actions/upload-artifact@v4
-        if: startsWith( matrix.go-version, '1.23' ) # only upload artifact for one version
+        if: startsWith( matrix.go-version, '~1.23' ) && github.ref == 'refs/heads/main' && github.event_name == 'push' # only upload artifact for one version and only on main
         with:
           name: test-results-${{ matrix.go-version }}-${{ matrix.runner }}-${{ matrix.group }}
           path: internal/tools/testresults/
           retention-days: 4
+      - name: Fail workflow if tests fails
+        if: steps.tests-with-junit.outcome == 'failure' || steps.tests.outcome == 'failure'
+        run: |
+          echo "Tests failed. Failing workflow."
+          exit 1
+          
   unittest:
     if: ${{ github.actor != 'dependabot[bot]' && always() }}
     runs-on: ubuntu-24.04
